export {default as Root} from "./root"
export {default as Homepage} from "./homepage/homepage"
export {default as Menu} from "./menu/menu"
export {default as Hakkımızda} from "./about/about"
export {default as Iletisim} from "./contact/contact"